Samvaad/Login/urls.py
from django.urls import path
from . import views

app_name = 'Login'

urlpatterns = [
    path('',views.LoginPage,name='login'),
]

Samvaad/Samvaad/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Login.urls')),
    path('newsfeed/',include('newsfeed.urls')),
]

Samvaad/newsfeed/urls.py
from django.urls import path
from . import views

app_name = 'newsfeed'

urlpatterns = [
    path('addCategory/',views.addCategory,name='addCategory'),
    path('addNewsfeed/',views.addNewsfeed,name='addNewsfeed'),
    path('viewNewsfeed/',views.viewNewsfeed,name='viewNewsfeed'),
]

Samvaad/Login/models.py
from django.db import models

# Create your models here.

class user_login_model(models.Model):
    user_name = models.CharField(max_length = 100)
    password = models.CharField(max_length = 100)
    status = models.CharField(max_length = 20)
    
    def __str__(self):
        return self.user_name + ' | ' + self.status

Samvaad/newsfeed/models.py
from django.db import models
import jsonfield
# Create your models here.

class Category(models.Model):
    category_name = models.CharField(max_length = 100,primary_key = True)
    category_fields = models.CharField(max_length = 1000)
    
    def __str__(self):
        return self.category_name + ' - ' + self.category_fields

class NewsFeed(models.Model):
    updated_by = models.CharField(max_length = 100)
    target_type = models.CharField(max_length = 20)
    content = models.CharField(max_length = 999)
    category = models.CharField(max_length = 20)
    score = jsonfield.JSONField()
    
    def __str__(self):
        return 'Updated by: ' + self.updated_by + ' score: ' + self.score

Samvaad/Login/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from django.urls import reverse
from Login.models import user_login_model

# Create your views here.


@csrf_exempt
def LoginPage(request):
    template = loader.get_template('LoginPage.html')
    error_message = ''
    
    if request.method == 'GET':
        return HttpResponse(template.render())
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        result = user_login_model.objects.filter(user_name=username,password=password)
        if result.count() != 1:
            error_message = 'Invalid'
        print(result)
        content = {
            'error_message': error_message,
        }
        return HttpResponse(template.render(content))
        # return HttpResponseRedirect('')

Samvaad/newsfeed/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from django.urls import reverse
from newsfeed.models import *
from newsfeed.form import addCategoryForm
import json
import paralleldots
# Create your views here.

paralleldots.set_api_key( "nUV2Ym1gQr8REXKIZQzgKQkDBUkBaUSK6Qukfcx4LwE" )

@csrf_exempt
def addCategory(request):
    addCategory_form = addCategoryForm()
    template = loader.get_template('addCategory.html')
    if request.method == 'GET':
        data = {
            'form':addCategory_form
        }
        return HttpResponse(template.render(data))
    if request.method == 'POST':
        input_category = request.POST.get('category_name')
        input_field = request.POST.get('category_fields')
        print(input_category)
        print(input_field)
        # Category received
        # Search it in tabel
        table_category = Category.objects.filter(category_name = input_category)
        print(table_category)
        # if not present add it to the table
        if table_category.count() == 0:
            addCategory_form = addCategoryForm(request.POST)
            addCategory_form.save()
            return HttpResponse("Table updated")
        # if present
        else:
            # print(table_category)
            # print(table_category[0].category_name)
            data = {
                'category_name':table_category[0].category_name,
                'category_fields':table_category[0].category_fields + input_field,
            }
            # addCategory_form = addCategoryForm(data)
            # addCategory_form.update()
            table_category = Category.objects.get(category_name=input_category)
            table_category.category_fields = table_category.category_fields + input_field
            table_category.save()
            return HttpResponse("Present : " + json.dumps(data))
        return HttpResponse("Post request")


# To add new Newsfeed
@csrf_exempt
def addNewsfeed(request):
    template = loader.get_template('addNewsfeed.html')
    if request.method == 'GET':
        return HttpResponse(template.render())
    else:
        # News feed to be added
        new_newsfeed = NewsFeed()
        new_newsfeed.updated_by = request.POST.get('updated_by')
        new_newsfeed.content = request.POST.get('content')
        new_newsfeed.target_type = ''
        new_newsfeed.category = ''
        categories = Category.objects.all()
        # print(categories[0])
        category = {}
        for cat in categories:
            category[cat.category_name] = json.loads('['+cat.category_fields+']')
            print(cat.category_name + ' ' + cat.category_fields)
        print(category)
        # It does not returns json objects
        # It returns in form = {'field':'value'}
        # but actual json is = { "field" : "value"}
        scores = paralleldots.custom_classifier( request.POST.get('content'), category )
        # score is dict
        print("Received: ")
        print(len(scores['taxonomy']))
        a = {}
        for score in scores['taxonomy']:
            print(score['tag'])
            print(score['confidence_score'])
            a[score['tag']] = score['confidence_score']
        
        # a = {}
        # for s in score['taxonomy']:
            # s = json.dumps(s)
            # a.append(s)
        # print("Final a : ")
        # print(a)
        # Covert score to pure string acceptable by python
        score = json.dumps(score)
        # To extract required info and remove other, covert back it to dict object
        # a = score['taxonomy'][0]
        new_newsfeed.score = a
        # print("News feed: " + new_newsfeed.score)
        # Calculatin score
        new_newsfeed.save();
        return HttpResponse("Added + " + json.dumps(category) + '<br>' + json.dumps(new_newsfeed.score))
        
def viewNewsfeed(request):
    newsfeeds = NewsFeed.objects.all();
    template = loader.get_template('viewNewsfeed.html')
    result = {}
    i = 0
    for news in newsfeeds:
        a = {}
        a['updated_by'] = news.updated_by
        a['content'] = news.content
        # print(news.score)
        # a['score'] = news.score
        # print(a['score'])
        result['newsfeed' + str(i)] = a
        print(news.score['language'])
        result['score' + str(i)] = news.score
        # print(result['newsfeed' + str(i)])
        i = i+1
    print(result)
    return HttpResponse(template.render({'data':result}))
    # score = newsfeeds[0].score
    # score = json.dumps(score)
    # print(json.loads(score))
    # score = json.loads(score)
    # data={
        # 'newsfeed' : score,
    # }
    # print("Data")
    # print(json.loads(data['newsfeed'])['taxonomy'])
    # return HttpResponse(template.render({'name':newsfeeds}))
    data = []
    for news in newsfeeds:
        # a = {}
        # a["updated_by"]  = news.updated_by
        # a["score"] = news.score
        # a["content"] = news.content
        # data.append(a)
        # -----------
        a = []
        a.append(news.updated_by)
        a.append(news.score)
        a.append(news.content)
        data.append(a)
    # data = json.dumps(data)
    # Just for futute refernce
    # Decode it 
    # print(json.loads(json.dumps(json.loads(data[0][1])['taxonomy'][0]))['tag'])
    return HttpResponse(template.render({'names':data}))
    

Samvaad/Login/templates/LoginPage.html
<!-- <!DOCTYPE html> -->
{% load static %}
<html>
<title>
  Login Page
</title>

<link href="{% static '/css/LoginPage.css' %}" rel="stylesheet">
<script src="{% static '/js/LoginPage.js' %}" type="text/javascript"></script>

<body style="padding:0px;margin: 0px;box-sizing: border-box;overflow: hidden">
  <!-- NavBar -->
  <nav class="navbarBody" style="padding:0px;text-align:left;">
    <br>
    <span style="color: white;font-size: 2.5em;">SANVAD</span>
  </nav>

  <!-- NavBar ends -->
  <!-- Middle Section -->
  <div class="middle">

    <div class="middleEnvelope">
      <!-- Login Box -->
      <form action="{% url 'Login:login' %}" method="POST">
        <div class="loginBox">
          <span style="font-size: 2em;font-family:Sofia">Login</span>
          <hr>
          <br>
          <input type="text" placeholder="Enter Username" name="username" class="loginInput">
          <br>
          <br>
          <input type="password" placeholder="Enter Password" name="password" class="loginInput">
          <br><br>
          <input type="submit" value="LOGIN"  class="loginButton">
          <br>
          <br>
          <hr>
					{% if error_message %}
						<span style="color:red">
						{{ error_message }}
						</span>
					{% endif %}
        </div>
      </form>
      <!-- Login Box ends -->
    </div>
  </div>
  <!-- Middle Section ends -->
  <!-- Footer  -->
  <div class="footer">
    <br>
    <center>
      Developed by: <b>TEAM TRIANGULATION</b>
    </center>
  </div>
  <!-- Footer ends -->
</body>
</html>

Samvaad/newsfeed/templates/addCategory.html
{% load staticfiles %}
<html>
<title>Add Category</title>
<body>
  You are in here
  <!-- <form action="{% url 'newsfeed:addCategory' %}" method="POST">
    Category:
    <input type="text" name="category">
    <br>
    Fields:
    <input type="text" name="field">
    <br>
    <button type="submit">submit</button>
  </form> -->
  <form action="{% url 'newsfeed:addCategory' %}" method="POST">
    {{ form }}
    <button type="submit">Submit</button>
  </form>
</body>
</html>

Samvaad/newsfeed/templates/addNewsfeed.html
<html>
<title>Add newsfeed page</title>
<body>
  <form method="POST" action="{% url 'newsfeed:addNewsfeed' %}">
    <input type="text" name="updated_by" placeholder="User name">
    <br>
    <textarea name="content" placeholder="content"></textarea>
    <br>
    <button type="submit">Update</button>
  </form>
</body>
</html>

Samvaad/newsfeed/templates/viewNewsfeed.html
{% load static %}
<html>
<title>View News Feed</title>
<body>
  View newsfeed page<br>
{{ data }}
<br>
<br>
{{ data.newsfeed0.updated_by}}
<br>
{{ data.score0.ArtificialIntelligence }}
<br>
{% for a in data.newsfeed0.score %}
{{ a }}
{% endfor %}
<div id="abc"></div>
<br><br>
{% for r in data %}
{{ r }}
<br>
  {% for s in r %}
    print{{ s }}
    <br>
  {% endfor %}
{% endfor %}
</body>
<script>
// value='{{ name}}';
</script>
<!-- <script type="text/javascript" src="{% static 'viewNewsfeed.js' %}"></script> -->
</html>